# Generated by Django 3.1.4 on 2020-12-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.IntegerField(default='请输入设备id', verbose_name='设备id')),
                ('dev_name', models.TextField(default='请输入设备名称', verbose_name='设备名称')),
                ('dev_desc', models.TextField(default='请输入设备描述', verbose_name='设备描述')),
                ('dev_paras', models.TextField(default='请输入设备参数', verbose_name='设备参数')),
            ],
            options={
                'verbose_name': '设备列表',
                'verbose_name_plural': '设备列表',
                'db_table': 'device_info',
            },
        ),
    ]
