# Generated by Django 3.1.4 on 2020-12-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceInfo',
        ),
    ]
